auto:
    create:
        topics:
            enable: true
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-service:8761/eureka
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8080
    servlet:
        context-path: /api/v1
spring:
    application:
        name: MICROSERVICE-1
    cloud:
        config:
            profile: local
    config:
        import: optional:configserver:http://config-server:8888
    kafka:
        producer:
            bootstrap-servers: kafka:9092
            group-id: group_id
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
    rabbitmq:
        host: rabbitmq
        password: guest
        port: 5672
        username: guest
topic:
    name:
        producer: topic.test