name: Docker Compose CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Harbor
      uses: docker/login-action@v2.1.0
      with:
        registry: demo.goharbor.io
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    - name: Build Microservices
      run:  docker-compose -f "docker-compose.yml" up -d --build
    - name: Push Microservices to harbor
      run:  docker-compose -f "docker-compose.yml" push
